package be.com.intro.grpc.client.rpctypes;

import br.com.intro.grpc.model.*;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts;
import io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder;
import io.grpc.netty.shaded.io.netty.handler.ssl.SslContext;
import io.grpc.stub.StreamObserver;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import javax.net.ssl.SSLException;
import java.io.File;
import java.util.concurrent.CountDownLatch;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class BankClientTest {

    private BankServiceGrpc.BankServiceBlockingStub bankServiceBlockingStub;
    private BankServiceGrpc.BankServiceStub bankServiceStub;

    @BeforeAll
    public void setup() throws SSLException {

        SslContext sslContext = GrpcSslContexts.forClient()
                .trustManager(new File("C:/system_development/ssl-tls/ssl generated by me/ca.cert.pem"))
                .build();

        ManagedChannel channel = NettyChannelBuilder.forAddress("localhost", 6565)
                .sslContext(sslContext)
                //.usePlaintext()
                .build();

        this.bankServiceBlockingStub = BankServiceGrpc.newBlockingStub(channel);
        this.bankServiceStub = BankServiceGrpc.newStub(channel);
    }

    @Test
    public void balanceTest(){
        BalanceCheckRequest balanceCheckRequest = BalanceCheckRequest.newBuilder()
                .setAccountNumber(7)
                .build();

        Balance balance = this.bankServiceBlockingStub.getBalance(balanceCheckRequest);
        System.out.println("Received: " + balance.getAmount());
    }

    @Test
    public void withDrawTest(){
        WithDrawRequest withDrawRequest = WithDrawRequest.newBuilder()
                .setAccountNumber(7)
                .setAmount(40)
                .build();

        this.bankServiceBlockingStub.withDraw(withDrawRequest)
                .forEachRemaining(money -> System.out.println("Received: "+ money.getValue()));
    }

    @Test
    public void withDrawAsyncTest() throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);

        WithDrawRequest withDrawRequest = WithDrawRequest.newBuilder()
                .setAccountNumber(10)
                .setAmount(80)
                .build();
        MoneyStreamResponse streamObserver = new MoneyStreamResponse(latch);

        this.bankServiceStub.withDraw(withDrawRequest, streamObserver);
        latch.await();
    }

    @Test
    public void cashStreamingRequest() throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);
        StreamObserver<Balance> balanceStreamObserver = new BalanceStreamObserver(latch);
        StreamObserver<DepositRequest> depositRequestStreamObserver = this.bankServiceStub.cashDeposit(balanceStreamObserver);
        for (int i = 0; i < 10; i++) {
            DepositRequest depositRequest = DepositRequest.newBuilder()
                    .setAccount(7)
                    .setAmount(10)
                    .build();
            depositRequestStreamObserver.onNext(depositRequest);
        }
        depositRequestStreamObserver.onCompleted();
        latch.await();;
    }
}
